#:schema node_modules/wrangler/config-schema.json
name = "wallo"
compatibility_date = "2024-10-11"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }

[observability]
enabled = true


[[d1_databases]]
binding = "DB"
database_name = "pluto"
database_id = "c364bad3-ca8f-491b-9432-add0f8334dcf"
